### ISSUE TITLE
Player can only move tiles within a certain radius

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [this-place/this.place#26]
Due to changes in the design, we must now restrict which blocks can be moved based on the player's location. As title mentions, we could use a radius of sorts.

**Comment by Rinder5** [comment]
details:
player must be ~1 space away to interact with a tile.
player will not walk to a tile if she is too far away.

if there is empty space or an obstacle behind the player, the player will pull the block out ~halfway, stop for a bit, then push it back in.

player can only push back blocks if she is facing the block from the correct direction
if there is a obstacle in the way, player will push the block futilely for a bit, then stop.

issue:
how do we indicate to the player which blocks are movable? If we only highlight on mouse-over, it's very easy to miss since most blocks are not movable.
